# stages:
#   - build
#   - push


# build-job:
#   stage: build
#   script:
#     echo "Build Job Completed"
  

# push-job:
#   stage: push
#   script:
#     echo "Push Job Done"





# Define stages in the pipeline
stages:
  - build
  - push

# Define variables
variables:
  DOCKER_IMAGE: "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA"

# Build the Docker image
build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay2
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $DOCKER_IMAGE .
  only:
    - main  # Run this job only on the 'main' branch

# Push the Docker image to the registry
push:
  stage: push
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay2
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push $DOCKER_IMAGE
  only:
    - main  # Run this job only on the 'main' branch
