name: Docker Image CI/CD

on:
  push:
    branches:
      # main is tenant1, tenant2 branch for other tenants
      - main
      - tenant2

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      DOCKER_IMAGE: sourav2805/nextjs-portfolio

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx 🚀
        uses: docker/setup-buildx-action@v3
      
      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Determine the tenant from branch name
      - name: Set Tenant Name
        id: tenant
        run: |
          # Extract the branch name (without refs/heads/)
          echo "TENANT=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      

      # Build and push Docker image to Docker Hub
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.DOCKER_IMAGE }}:${{ env.TENANT }}

      # Verify the image is pushed successfully
      - name: Verify Docker Image
        run: |
          echo "Docker image pushed: ${{ env.DOCKER_IMAGE }}:${{ env.TENANT }}"
