name: Build and Push Docker Images

on:
  push:
    branches:
      - tenant1
      - tenant2

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      DOCKER_IMAGE: sourav2805/nextjs-portfolio

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Extract branch name and set it as TENANT
      - name: Extract Tenant Name
        id: tenant
        run: |
          echo "TENANT=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV

      # Build and Push Docker Image
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.DOCKER_IMAGE }}:${{ env.TENANT }}

      # Verify Docker Image Push
      - name: Verify Docker Image
        run: |
          echo "Docker image pushed successfully: ${{ env.DOCKER_IMAGE }}:${{ env.TENANT }}"
